# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Punto_B1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from adafruit_servokit import ServoKit
from time import sleep

#---------------------------------
#---------configuro PCA---------- 
#---------------------------------
#kit = ServoKit(channels=16)
#servo = 16 #se coloca cuantos canales se van a usar
#kit.servo[0].set_pulse_width_range(600, 2500)
#kit.servo[1].set_pulse_width_range(600, 2500)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(200, 210, 261, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 140, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 90, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 310, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 310, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 370, 321, 71))
        self.label_7.setStyleSheet("border-image: url(:/cct/logo ECCI.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 370, 261, 91))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #---------------------------------
        #------configuro sliders----------
        #---------------------------------
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setValue(0)
        #----------------------------------
        #--------configuros acciones-------
        #----------------------------------
        self.horizontalSlider.valueChanged.connect(self.servo_select)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Uso manual servo"))
        self.label.setText(_translate("MainWindow", "Manejo manual servo motor"))
        self.label_2.setText(_translate("MainWindow", "ingrese el servo a controlar 1 o 2 "))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", ""))
        self.label_8.setText(_translate("MainWindow", "Daniel Ricardo Quiroga Contreras"))

    def servo_select(self):
        try:
            opcion = int(self.textEdit.toPlainText())
            if opcion == 1:
                valorslider = self.horizontalSlider.value()
                if valorslider > 1:
                    self.label_3.setText("Servo_1 on")
                    self.label_3.setStyleSheet("background-color: lightgreen")
                    self.label_5.setText(f"Grados: {valorslider}")
                    #kit.servo[0].angle= valorslider
                else:
                    self.label_3.setText("")
                    self.label_3.setStyleSheet("background-color: lightgray")
                    self.label_5.setText("")
                    
            if opcion == 2:
                valorslider = self.horizontalSlider.value()
                if valorslider >1:
                    self.label_4.setText("Servo_2 on")
                    self.label_4.setStyleSheet("background-color: lightgreen")
                    self.label_6.setText(f"Grados: {valorslider}")
                    #kit.servo[1].angle= valorslider
                else:
                    self.label_4.setText("")
                    self.label_4.setStyleSheet("background-color: lightgray")
                    self.label_6.setText(f"")
        except ValueError:
            print("Debe ingresar un dato numerico")   
        app.processEvents()  #linea importante para actualizar la ventana

        
        
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
