# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lectura_boton.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gpiozero import Button
button = Button(2)



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 230, 131, 51))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 240, 251, 51))
        self.label_3.setStyleSheet("border-image: url(:/cct/logo ECCI.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 30, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #/////////////////////////////////////////////////
        #///////acciones al presionar botones/////////////
        #/////////////////////////////////////////////////
   
        self.pushButton.clicked.connect(self.lectura)
        self.pushButton_2.clicked.connect(self.cerrar)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Daniel quiroga\n2\n2"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar lectura"))
        self.pushButton_2.setText(_translate("MainWindow", "Cerrar"))
    def lectura(self):
        while True:
           if button.is_pressed:
            print("Boton presionado")
            self.label_4.setText("ALTO")
            self.label_4.setStyleSheet("background-color: red") 
           else:
            print("Boton no presionado")
            self.label_4.setText("BAJO")
            self.label_4.setStyleSheet("background-color: blue") 
            # Forzar la actualización de la interfaz gráfica
           app.processEvents()  #linea importante para actualizar la ventana
           
    def cerrar(self):
       self.close()  # Comando para cerrar la ventana al hacer clic en el botón
        
        
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
