# -*- coding: utf-8 -*-



# Form implementation generated from reading ui file 'Punto_B3.ui'

#

# Created by: PyQt5 UI code generator 5.15.9

#

# WARNING: Any manual changes made to this file will be lost when pyuic5 is

# run again.  Do not edit this file unless you know what you are doing.





from PyQt5 import QtCore, QtGui, QtWidgets

import time

from mpu6050 import mpu6050

mpu = mpu6050(0x68)





class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")

        MainWindow.resize(734, 437)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)

        self.label.setGeometry(QtCore.QRect(420, 360, 271, 61))

        self.label.setStyleSheet("border-image: url(:/cct/logo ECCI.jpg);")

        self.label.setText("")

        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)

        self.label_2.setGeometry(QtCore.QRect(250, 30, 221, 41))

        font = QtGui.QFont()

        font.setPointSize(15)

        self.label_2.setFont(font)

        self.label_2.setObjectName("label_2")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)

        self.textEdit.setGeometry(QtCore.QRect(110, 110, 61, 41))

        font = QtGui.QFont()

        font.setPointSize(12)

        self.textEdit.setFont(font)

        self.textEdit.setObjectName("textEdit")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)

        self.label_3.setGeometry(QtCore.QRect(50, 80, 231, 21))

        font = QtGui.QFont()

        font.setPointSize(9)

        self.label_3.setFont(font)

        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)

        self.label_4.setGeometry(QtCore.QRect(20, 310, 291, 111))

        font = QtGui.QFont()

        font.setPointSize(11)

        self.label_4.setFont(font)

        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label_4.setObjectName("label_4")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton.setGeometry(QtCore.QRect(80, 180, 131, 31))

        font = QtGui.QFont()

        font.setPointSize(10)

        self.pushButton.setFont(font)

        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton_2.setGeometry(QtCore.QRect(80, 230, 131, 31))

        font = QtGui.QFont()

        font.setPointSize(10)

        self.pushButton_2.setFont(font)

        self.pushButton_2.setObjectName("pushButton_2")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)

        self.label_5.setGeometry(QtCore.QRect(370, 140, 211, 21))

        self.label_5.setText("")

        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)

        self.label_6.setGeometry(QtCore.QRect(370, 160, 211, 21))

        self.label_6.setText("")

        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)

        self.label_7.setGeometry(QtCore.QRect(370, 180, 211, 21))

        self.label_7.setText("")

        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)

        self.label_8.setGeometry(QtCore.QRect(370, 200, 211, 21))

        self.label_8.setText("")

        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)

        self.label_9.setGeometry(QtCore.QRect(370, 220, 211, 21))

        self.label_9.setText("")

        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)

        self.label_10.setGeometry(QtCore.QRect(370, 250, 211, 21))

        self.label_10.setText("")

        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)

        self.label_11.setGeometry(QtCore.QRect(370, 270, 211, 21))

        self.label_11.setText("")

        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)

        self.label_12.setGeometry(QtCore.QRect(370, 290, 211, 21))

        self.label_12.setText("")

        self.label_12.setObjectName("label_12")

        MainWindow.setCentralWidget(self.centralwidget)



        #--------------------------------------

        #-------accionnes de los botones-------

        #--------------------------------------

        self.pushButton.clicked.connect(self.medicion)

        self.pushButton_2.clicked.connect(self.cerrar)

        

        

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Lectura I2C"))

        self.label_2.setText(_translate("MainWindow", "Lectura sensor I2C"))

        self.label_3.setText(_translate("MainWindow", "asigne un tiempo de lectura (seg)"))

        self.label_4.setText(_translate("MainWindow", "Daniel ricardo quiroga"))

        self.pushButton.setText(_translate("MainWindow", "iniciar lectura"))

        self.pushButton_2.setText(_translate("MainWindow", "Salir"))

    def medicion(self):
        user_time = int(self.textEdit.toPlainText())        #capturo valor del edit text (segundos de lectura)
        t1 = time.time()                                    #inicio tempp
        t2 = 0.0                                            
        t_user = user_time                                  #camio de 
        while t2<= t_user:
            t2 = time.time() - t1
            tiempo_transcurrido = float(t2)
            self.label_5.setText (f'tiempo transcurrido: {tiempo_transcurrido:.2f}')
            temperatura = mpu.get_temp()
            print(f'temperatura: {temperatura:.2f}' )
            self.label_6.setText (f'temperatura: {temperatura:.2f}')
            accel_data = mpu.get_accel_data()
            acc_x = (accel_data['x'])
            acc_y = (accel_data['y'])
            acc_z = (accel_data['z'])
            print(f'Acc X : {acc_x:.2f}')
            self.label_7.setText (f'Aceleracion X: {acc_x:.2f}')
            print(f'Acc Y : {acc_y:.2f}')
            self.label_8.setText (f'Aceleracion Y: {acc_y:.2f}')
            print(f'Acc Z : {acc_z:.2f}')
            self.label_9.setText (f'Aceleracion Z: {acc_z:.2f}')
            print()
            gyro_data = mpu.get_gyro_data()
            giro_x = (gyro_data['x'])
            giro_y = (gyro_data['y'])
            giro_z = (gyro_data['z'])
            print(f'giro en x : {giro_x:.2f}')
            self.label_10.setText (f'Giro X: {giro_x:.2f}')
            print(f'giro en Y : {giro_y:.2f}')
            self.label_11.setText (f'Giro Y: {giro_y:.2f}')
            print(f'giro en x : {giro_z:.2f}')
            self.label_12.setText (f'Giro Z: {giro_z:.2f}')

            print()

            print("-------------------------------")

            

            

            app.processEvents()  #linea importante para actualizar la ventana

        



    def cerrar(self):

        self.close()  # Comando para cerrar la ventana al hacer clic en el botón

import logo_rc





if __name__ == "__main__":

    import sys

    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()

    ui.setupUi(MainWindow)

    MainWindow.show()

    sys.exit(app.exec_())

